[REFACTOR] 프로젝트 리팩터링
rlfrkdms1/Prog-rangers pull request #111
Opened 2023-09-07 08:12 UTC by jd99iam

## #106 

### 💡 PR 타입(하나 이상의 PR 타입을 선택해주세요)
* [ ] 리팩터링

### 📲 반영 브랜치
ex) refactor/106-refactor-project -> 1-develop

### ❔ 변경 사항
프로젝트를 리팩터링했습니다
- 메서드 추출 
- 변수명 변경
- 반복문을 stream 활용하도록 변경 
등 가독성 향상에 초점을 두고 리팩터링 했습니다

### 🔍 테스트 결과

### 📰 참고 Reference

### ⚒️ 기타 사항

2023-09-07 09:44 UTC, rlfrkdms1 requested changes

2023-09-07 09:44 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/review/response/SolutionReview.java
> +    public static SolutionReview from(com.prograngers.backend.entity.Review review){
`com.prograngers.backend.entity.Review review`라고 되어있네요 !

2023-09-07 09:44 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/SolutionPatchRequest.java
>      public Solution toSolution(Solution target) {
toSolution이면 solution을 만드는 메서드가 돼야 할 것 같은데 update를 하고 있네요 ..?

2023-09-07 09:44 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +        response.comments = commentResponseList;
왜 이렇게 전부 .을 찍어서 하는건가요 ? setter를 사용하고 싶었던건가요 ?

2023-09-07 09:44 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +                .forEach(comment-> commentResponseList.add( new SolutionDetailComment(
SolutionDetailComment에 from(Comment comment) 만들면 더 깔끔할 것 같아요

2023-09-07 09:44 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +                            parentComment.getReplies().add(new SolutionDetailComment(comment.getMember().getPhoto(), comment.getId(), comment.getMember().getNickname(), comment.getContent(), comment.
이것도 from 으로 더 간단해질 수 있을 것 같아요

2023-09-07 09:44 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/solution/Solution.java
> +    public void update(String title, AlgorithmConstant algorithm, DataStructureConstant dataStructure, int level, String code, String description){
파라미터로 Solution을 받아오는게 어떤가요 ?

2023-09-08 06:11 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/review/response/SolutionReview.java
> +    public static SolutionReview from(com.prograngers.backend.entity.Review review){
> `com.prograngers.backend.entity.Review review`라고 되어있네요 !

수정했습니다

2023-09-08 06:13 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/reqeust/SolutionPatchRequest.java
>      public Solution toSolution(Solution target) {
> toSolution이면 solution을 만드는 메서드가 돼야 할 것 같은데 update를 하고 있네요 ..?

SolutionPatchRequest의 toSolution이라서 update를 하는데 updateSolution이 더 맞을 것 같아서 수정하겠습니다

2023-09-08 06:18 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +        response.comments = commentResponseList;
> 왜 이렇게 전부 .을 찍어서 하는건가요 ? setter를 사용하고 싶었던건가요 ?

setter로 다 수정하고 메서드 추출했습니다

2023-09-09 04:07 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +                .forEach(comment-> commentResponseList.add( new SolutionDetailComment(
> SolutionDetailComment에 from(Comment comment) 만들면 더 깔끔할 것 같아요

수정했습니다

2023-09-09 04:08 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +                            parentComment.getReplies().add(new SolutionDetailComment(comment.getMember().getPhoto(), comment.getId(), comment.getMember().getNickname(), comment.getContent(), comment.
> 이것도 from 으로 더 간단해질 수 있을 것 같아요

수정했습니다

2023-09-09 04:10 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/entity/solution/Solution.java
> +    public void update(String title, AlgorithmConstant algorithm, DataStructureConstant dataStructure, int level, String code, String description){
> 파라미터로 Solution을 받아오는게 어떤가요 ?

SolutionPatchRequest에서 Solution을 update 할 때 사용하는 메서드라 말씀하신 대로 수정하려면 
굳이 Solution을 생성해서 인자로 전달해야 해서 그럴 필요는 없을 것 같습니다

2023-09-09 04:13 UTC, rlfrkdms1 approved these changes

2023-09-09 04:13 UTC, merged