[REFACTOR] 가독성을 위한 리팩터링
rlfrkdms1/Prog-rangers pull request #117
Opened 2023-09-11 23:04 UTC by jd99iam

## #116 

### 💡 PR 타입(하나 이상의 PR 타입을 선택해주세요)
* [ ] 리팩터링

### 📲 반영 브랜치
ex) refactor/116-project -> 1-develop

### ❔ 변경 사항
for문을 최대한 줄이고 가독성을 위해 stream을 사용했습니다
반복문을 돌며 dto에 더하는 코드를 수정해서 stream을 바로 배열로 만들도록 했습니다
메서드를 최대한  추출해서 가독성을 좋게 했습니다

### 🔍 테스트 결과

### 📰 참고 Reference

### ⚒️ 기타 사항
SolutionPostRequest의 toProblem에서 ProblemRepository를 인자로 받아서 저장하는데, dto에서 problemRepository를 인자로 받아서 처리하는 것에 대해 의견이 궁금합니다

2023-09-12 01:42 UTC, rlfrkdms1 requested changes

2023-09-12 01:42 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/member/response/MemberProfileResponse.java
>          } else {
`else` 예약어를 사용하지 않는 방법은 없을까요 ?

2023-09-12 01:42 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/review/response/SolutionReviewsResponse.java
>              SolutionLine solutionLine = SolutionLine.builder()
solutionLine에 대한 정적 팩토리 메서드는 없나요 ?

2023-09-12 01:42 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +                .forEach(comment-> commentResponseList.add(new SolutionDetailComment(comment.getMember().getPhoto(), comment.getId(), comment.getMember().getNickname(), comment.getContent(), comment.
SolutionDetailComment에 from 메서드를 만들면 SoltionDetailComment.from(comment)로 해결 될 것 같아요

2023-09-12 01:42 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
>          comments.stream().filter(comment -> comment.getParentId()==null)
`comments.stream().filter(comment -> comment.getParentId()==null).map(SolutionDetailComment::from).collect(Collectors.toList())` 와 같은 방식으로 하는 건 어떤가요 ?

2023-09-12 01:42 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/ProblemService.java
> +    private static void addTagToProblemListProblem(ProblemListProblem problemListProblem, List<Solution> solutions) {
static 메서드인 이유가 있나요 ?

2023-09-12 04:52 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/member/response/MemberProfileResponse.java
>          } else {
> `else` 예약어를 사용하지 않는 방법은 없을까요 ?

여기서는 불가피해 보입니다

2023-09-13 13:49 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/member/response/MemberProfileResponse.java
>          } else {
> `else` 예약어를 사용하지 않는 방법은 없을까요 ?

커서값으로 마지막인지 알 수 있으니 isLast를 사용하지 않도록 하고 else문을 뺐습니다

2023-09-13 13:54 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/review/response/SolutionReviewsResponse.java
>              SolutionLine solutionLine = SolutionLine.builder()
> solutionLine에 대한 정적 팩토리 메서드는 없나요 ?

수정했습니다

2023-09-13 14:06 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
> +                .forEach(comment-> commentResponseList.add(new SolutionDetailComment(comment.getMember().getPhoto(), comment.getId(), comment.getMember().getNickname(), comment.getContent(), comment.
> SolutionDetailComment에 from 메서드를 만들면 SoltionDetailComment.from(comment)로 해결 될 것 같아요

수정했습니다

2023-09-13 14:26 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionDetailResponse.java
>          comments.stream().filter(comment -> comment.getParentId()==null)
> `comments.stream().filter(comment -> comment.getParentId()==null).map(SolutionDetailComment::from).collect(Collectors.toList())` 와 같은 방식으로 하는 건 어떤가요 ?

수정했습니다

2023-09-13 14:28 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/ProblemService.java
> +    private static void addTagToProblemListProblem(ProblemListProblem problemListProblem, List<Solution> solutions) {
> static 메서드인 이유가 있나요 ?

static 뺐습니다

2023-09-14 02:36 UTC, jd99iam commented
SolutionPostRequest의 toProblem 수정했습니다

2023-09-14 12:44 UTC, rlfrkdms1 approved these changes

2023-09-14 12:44 UTC, merged