[FEAT] 리뷰 작성, 수정, 삭제 기능 개발
rlfrkdms1/Prog-rangers pull request #121
Opened 2023-09-14 05:19 UTC by jd99iam

## #118 

### 💡 PR 타입(하나 이상의 PR 타입을 선택해주세요)
* [ ] 기능 추가
* [ ] 테스트코드 작성

### 📲 반영 브랜치
ex) feat/118-write-review -> 1-develop

### ❔ 변경 사항
리뷰 작성 기능을 추가했습니다
리뷰 수정 기능을 추가했습니다
리뷰 삭제 기능을 추가했습니다

### 🔍 테스트 결과
- Service 테스트
내 리뷰 아닌 리뷰 수정, 삭제 시 예외 발생 테스트 추가
이미 삭제된 리뷰 수정, 삭제 시 예외 발생 테스트 추가

### 📰 참고 Reference

### ⚒️ 기타 사항

2023-09-15 07:33 UTC, rlfrkdms1 requested changes

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/controller/ReviewController.java
> +    private ResponseEntity<Object> redirect(Long solutionId) {
왜 ResponseEntity<Object>를 반환하나요 ? 그냥 ResponseEntity<Void>를 반환하면 안되는걸까요 ?

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/review/request/ReviewPostRequest.java
> +    @NotNull
int인데 `NotNull`을 사용하면 적용이 안될 것 같아요

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +        Solution solution = solutionRepository.findById(solutionId).orElseThrow(SolutionNotFoundException::new);
줄을 합칠 수 있을 것 같아요

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    public void writeReview(ReviewPostRequest reviewPostRequest, Long memberId,Long solutionId) {
service클래스에 `@Transactional` 빠졌어요

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    private static void checkReviewAlreadyDeleted(Review targetReview) {
저희 다 `valid`로 통일했던 것 같아요

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    private static void checkMemberAuthorization(Review targetReview, Member member) {
`static`이 왜 사용된 걸까요 ?

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    public void deleteReview(Long memberId, Long reviewId) {
여기는 `review`가 여러개 사용되지 않았는데 왜 targetReview인가요 ?

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
상태가 status로 변경될 때 content 내용도 바뀌어야 되지 않을까요 ?

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
solution의 알고리즘, 자료구조가 필수 항목이 아닌데, 이들이 필요없는 테스트에서 사용될 필요가 있을까요 ?

2023-09-15 07:33 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +    ReviewPatchRequest 리뷰_수정_요청_생성(){
접근 제한자가 누락된 것 같네요,

2023-09-16 06:03 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/controller/ReviewController.java
> +    private ResponseEntity<Object> redirect(Long solutionId) {
> 왜 ResponseEntity를 반환하나요 ? 그냥 ResponseEntity를 반환하면 안되는걸까요 ?

수정했습니다

2023-09-16 06:04 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/review/request/ReviewPostRequest.java
> +    @NotNull
> int인데 `NotNull`을 사용하면 적용이 안될 것 같아요

수정했습니다

2023-09-16 06:06 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +        Solution solution = solutionRepository.findById(solutionId).orElseThrow(SolutionNotFoundException::new);
> 줄을 합칠 수 있을 것 같아요

수정했습니다

2023-09-16 06:09 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    private static void checkReviewAlreadyDeleted(Review targetReview) {
> 저희 다 `valid`로 통일했던 것 같아요

수정했습니다

2023-09-16 06:12 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    private static void checkMemberAuthorization(Review targetReview, Member member) {
> `static`이 왜 사용된 걸까요 ?

불필요한 static 삭제했습니다

2023-09-16 06:16 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/ReviewService.java
> +    public void deleteReview(Long memberId, Long reviewId) {
> 여기는 `review`가 여러개 사용되지 않았는데 왜 targetReview인가요 ?

수정했습니다

2023-09-16 06:17 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
> 상태가 status로 변경될 때 content 내용도 바뀌어야 되지 않을까요 ?

리뷰나 댓글 내용은 놔두고 status로 관리하기로 한 걸로 이해했는데 아닌가요?

2023-09-16 06:27 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
> solution의 알고리즘, 자료구조가 필수 항목이 아닌데, 이들이 필요없는 테스트에서 사용될 필요가 있을까요 ?

알고리즘, 자료구조 필수 항목입니다

2023-09-16 06:28 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +    ReviewPatchRequest 리뷰_수정_요청_생성(){
> 접근 제한자가 누락된 것 같네요,

추가했습니다

2023-09-16 18:51 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
`삭제된 댓글입니다`라고 뜨지 않고 그냥 그대로 두는건가요 ? 그렇다면 삭제의 이유가 있을까요 ?

2023-09-16 18:52 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
init.sql 보면 필수 항목 아니라고 지정하기로 했는데, 필수항목이라고 하신 근거가 뭔가요 ?

2023-09-17 00:37 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
> `삭제된 댓글입니다`라고 뜨지 않고 그냥 그대로 두는건가요 ? 그렇다면 삭제의 이유가 있을까요 ?

전에 content를 `삭제된 댓글입니다` 로 뜨게 하면 사용자가 댓글을 `삭제된 댓글입니다` 로 입력한 것이랑 구분이 안 된다고 하시지 않으셨나요?

2023-09-17 00:38 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
> init.sql 보면 필수 항목 아니라고 지정하기로 했는데, 필수항목이라고 하신 근거가 뭔가요 ?

풀이 작성할 때 알고리즘, 자료구조는 필수로 있어야 하지 않나요? init.sql을 수정해야 할 것 같습니다

2023-09-17 04:28 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
content를 `삭제된 댓글입니다`로만 고치면 구분이 안되서 status를 추가하자고 말씀드렸던 겁니다 !

2023-09-17 04:29 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
init.sql 은 저희가 같이 수정하고 만든건데, 왜 필수가 아닐지 생각해보면 좋을 것 같아요.
queue를 사용한 경우엔 자료구조만 사용한 경우인데, 알고리즘은 넣을게 없는 경우가 생기지 않을까요 ?

2023-09-17 04:51 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
> content를 `삭제된 댓글입니다`로만 고치면 구분이 안되서 status를 추가하자고 말씀드렸던 겁니다 !

이해했습니다! content도 수정되도록 바꿨습니다. 
그렇다면 프론트 분들과 상의해서 `STATUS = DELETED` 인 경우 클라이언트에게 뭔가 다르게 보여지도록 해야 STATUS를 넣은 의미가 있을 것 같아요!

2023-09-17 04:59 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/review/Review.java
> +        this.status=DELETED;
좋습니다 ~ 회의 안건에 적어놓도록 하겠습니다

2023-09-17 05:41 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
> init.sql 은 저희가 같이 수정하고 만든건데, 왜 필수가 아니라고 결론지었을지 생각해 보면 좋을 것 같아요. queue를 사용한 경우엔 자료구조만 사용한 경우인데, 알고리즘은 넣을게 없는 경우가 생기지 않을까요 ?

말씀 들어보니 맞는 것 같습니다.
그렇다면 풀이 생성할 때 알고리즘, 자료구조 둘 다 null일수도 있는 걸까요?
사용자가 정한 알고리즘, 자료구조 중에 특별히 사용한 게 없다고 생각할 수도 있지 않을까요?

2023-09-19 08:01 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
그런 경우를 방지하려면 service 단에서 검증하면 될 것 같습니다 DB 단에서 검증할 방법은 없을 것 같아요

2023-09-19 08:03 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
음 둘 다 null인 경우도 허용해야된다는 말씀이실까요 ?
저는 사실 둘 다 null인 경우도 허용해야 된다는 입장입니다.
태그는 분류를 통한 편의를 제공하는 기능이지 필수 기능은 아니라고 생각해서요

2023-09-19 08:14 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +                    if (commentReplyResponse.getNickname().equals(member.getNickname())) commentReplyResponse.setMine(true);
`setMine` 말고 다른 작명이 좋을 것 같아요.
DTO 단에서의 setter 사용은 자유롭게 사용하는걸까요 ?

2023-09-19 08:14 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +    private void setCommentMine(Member member, List<SolutionDetailComment> solutionDetailComments) {
setCommentMine을 따로 하지 말고 댓글 response를 만들때 같이 검증할 순 없나요 ?

2023-09-20 08:01 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
> 음 둘 다 null인 경우도 허용해야된다는 말씀이실까요 ? 저는 사실 둘 다 null인 경우도 허용해야 된다는 입장입니다. 태그는 분류를 통한 편의를 제공하는 기능이지 필수 기능은 아니라고 생각해서요

넵 알겠습니다

2023-09-20 08:02 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
> > 음 둘 다 null인 경우도 허용해야된다는 말씀이실까요 ? 저는 사실 둘 다 null인 경우도 허용해야 된다는 입장입니다. 태그는 분류를 통한 편의를 제공하는 기능이지 필수 기능은 아니라고 생각해서요
> 
> 넵 알겠습니다

픽스처 수정해서 알고리즘, 자료구조 없이 사용할 수 있도록 하겠습니다

2023-09-20 08:03 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
제가 올린 것 중에 있습니다 사용하시면 될 것 같아요 !

2023-09-20 08:04 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +                    if (commentReplyResponse.getNickname().equals(member.getNickname())) commentReplyResponse.setMine(true);
> `setMine` 말고 다른 작명이 좋을 것 같아요. DTO 단에서의 setter 사용은 자유롭게 사용하는걸까요 ?

DTO에서의 setter 사용은 상관 없다고 하시지 않으셨나요?

2023-09-20 08:05 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +    private void setCommentMine(Member member, List<SolutionDetailComment> solutionDetailComments) {
> setCommentMine을 따로 하지 말고 댓글 response를 만들때 같이 검증할 순 없나요 ?

검증 로직을 서비스 단에서 하자고 하셔서 이렇게 수정한 것입니다..

2023-09-20 08:15 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/service/ReviewServiceTest.java
> +        Solution solution = 공개_풀이.아이디_지정_생성(1L,problem,member1, LocalDateTime.now(),DFS,LIST,JAVA,1);
> 제가 올린 것 중에 있습니다 사용하시면 될 것 같아요 !

그럼 merge 후에 수정하도록 하겠습니다

2023-09-20 08:18 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +    private void setCommentMine(Member member, List<SolutionDetailComment> solutionDetailComments) {
밑에 서비스 단에서 댓글 response를 만들어서 넣고 있지 않나요 ?

2023-09-20 08:19 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +                    if (commentReplyResponse.getNickname().equals(member.getNickname())) commentReplyResponse.setMine(true);
제가 그렇게 말씀 드렸나요 ?_? 알겠습니당

2023-09-20 08:25 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +    private void setCommentMine(Member member, List<SolutionDetailComment> solutionDetailComments) {
> 밑에 서비스 단에서 댓글 response를 만들어서 넣고 있지 않나요 ?

수정했습니다!!

2023-09-21 03:54 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +            commentResponseList.add(SolutionDetailComment.from(comment, new ArrayList<>(), false));
if 문 안쓰고 그냥 `commentResponseList.add(SolutionDetailComment.from(comment, new ArrayList<>(), validCommentIsMine(memberId, comment)));`로 변경하면 될 것 같은데요 ?
그리고 valid 말고 그냥 IsCommentMine이나 IsMine등으로 변경하는게 좋을 것 같습니다. valid는 검증할 때 사용하는 건데 해당 메서드는 검증과는 거리가 멀어보여요

2023-09-21 05:05 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +            commentResponseList.add(SolutionDetailComment.from(comment, new ArrayList<>(), false));
> if 문 안쓰고 그냥 `commentResponseList.add(SolutionDetailComment.from(comment, new ArrayList<>(), validCommentIsMine(memberId, comment)));`로 변경하면 될 것 같은데요 ? 그리고 valid 말고 그냥 IsCommentMine이나 IsMine등으로 변경하는게 좋을 것 같습니다. valid는 검증할 때 사용하는 건데 해당 메서드는 검증과는 거리가 멀어보여요

수정했습니다!

2023-09-21 10:14 UTC, rlfrkdms1 approved these changes

2023-09-21 10:14 UTC, merged