[FEAT] 내 풀이 상세보기
rlfrkdms1/Prog-rangers pull request #145
Opened 2023-09-26 11:19 UTC by jd99iam

## #132 

### 💡 PR 타입(하나 이상의 PR 타입을 선택해주세요)
* [ ] 기능 추가
* [ ] 기능 삭제
* [ ] 버그 수정
* [ ] 테스트코드 작성
* [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 📲 반영 브랜치
feature/132-my-solution-detail -> develop

### ❔ 변경 사항

### 🔍 테스트 결과
- Repo 테스트
- Service 테스트
- Controler 테스트

### 📰 참고 Reference
 
### ⚒️ 기타 사항
테스트 아직 작성안했습니다

2023-09-28 13:32 UTC, rlfrkdms1 requested changes

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/controller/SolutionController.java
> +        return ResponseEntity.ok().body(showMySolutionDetailResponse);
그전부터 궁금했는데, 그냥 DTO를 반환하면 되는데 ResponseEntity를 붙이는 이유는 뭔가요 ?

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/problem/response/ShowProblemListResponse.java
> +
띄어쓰기가 되어있네요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/problem/response/ShowProblemListResponse.java
> +        return new ShowProblemListResponse(listProblems,totalCount,page);
Builder로 통일하자고 하지 않았나요 ?

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/review/response/CodeWithCodeLineNumberAndReviewResponse.java
> +    private List<ReviewWithRepliesResponse> reviewWithRepliesResponse;
클래스명은 컨벤션에 맞춰도, 필드명까지 이렇게 맞출 필요는 없을 것 같아요
그냥 reviews 라던가 ?

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/review/response/CodeWithCodeLineNumberAndReviewResponse.java
> +public class CodeWithCodeLineNumberAndReviewResponse {
그냥 CodeLineWithReview가 되어도 될 것 같지 않나요 ?

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/CommentWithRepliesResponse.java
> +    String photo;
접근제한자 다 빠져있네요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/MainSolutionResponse.java
> +public class MainSolutionResponse {
Main 말고 그냥 Solution으로 가도 될 것 같다고 말씀 드린 것 같은데, 왜 Main인가요 ?
제가 보기엔 차라리 MySolution으로 가도 될 것 같습니다.

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/ReviewWIthRepliesResponse.java
> +public class ReviewWIthRepliesResponse {
오타 났어요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/ShowMySolutionDetailResponse.java
> +    // 문제
필요 없는 주석들 같습니다.

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/ShowSolutionDetailWithProblemAndCommentsResponse.java
> +public class ShowSolutionDetailWithProblemAndCommentsResponse {
여기는 그냥 ShowSolutionDetailResponse라고 가도 될 것 같은데욤 ..

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionAtSolutionListResponse.java
> +public class SolutionAtSolutionListResponse {
SolutionAtSolutionListResponse는 이상한 것 같아요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionListResponse.java
> +    List<SolutionAtSolutionListResponse> solutionAtSolutionListResponses;
필드명은 그냥 solutions가 되어도 될 것 같아요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/comment/Comment.java
> +    private static final String DELETED_CONTENT = "삭제된 댓글입니다";
이거 제가 밑으로 옮겨놓은건데 다시 위로 옮긴 이유가 있나요 ?

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepositoryImpl.java
> +                .limit(6)
매직넘버는 안쓰면 좋을 것 같아요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
>          // 댓글 response 만들기
이런 주석 다 삭제 하는게 좋을 것 같아요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +        List<Solution> solutionList = solutionRepository.findAllByProblem(mainSolution.getProblem());
정렬을 안하고 있는 것 같아요, 그리고 위의 mainSolution 또한 solutionList에 포함되어있을텐데, solutionList에서 찾는게 아니라 select절을 한번 더 날리는 이유가 궁금합니다.

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +        int likes = likesRepository.findAllBySolution(mainSolution).size();
count 메서드도 사용할 수 있는 걸로 알고 있습니다. 
countBySolution등을 사용해보면 어ㅈ떨까요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +        return solutionRepository.findAllByProblem(problem)
member 도 where절에 들어가야 할 것 같은데 아닌가요 ? problem으로만 찾으면 남이 스크랩한 풀이도 들어갈 것 같아요.

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +                .stream().filter(solution -> solution.getScrapSolution() != null)
이건 쿼리문에 걸 수 있는 제약 아닌가요 ?

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
> +        assertThat(result).containsExactly(solution1,solution2,solution3,solution4,solution5,solution6);
위에 모든걸 다 순서대로 해놓으셔서, 저장순인지 좋아요순인지 알 수 없을 것 같아요

2023-09-28 13:32 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
> +    @DisplayName("문제가 주어졌을 때 좋아요 순으로 상위 6개의 풀이를 정렬해서 가져올 수 있다")
차라리 find 쿼리의 limit를 동적으로 받아서 상위 6개 풀이를 가져올 수 있는걸 테스트 하지 마시고 1 ~ 2개 정도로 테스트 하는걸로 바꾸는게 어떤가요 ? 추후에 바뀔 수 있는 내용이잖아요 ?

2023-09-29 02:36 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/controller/SolutionController.java
> +        return ResponseEntity.ok().body(showMySolutionDetailResponse);
> 그전부터 궁금했는데, 그냥 DTO를 반환하면 되는데 ResponseEntity를 붙이는 이유는 뭔가요 ?

![image](https://github.com/rlfrkdms1/Prog-rangers/assets/96513365/eb9f2a4d-38d3-4602-8098-5402aa4c7401)
[ResponseEntity vs dto](https://yeonyeon.tistory.com/257)
그냥 dto로 반환하면 `@ResponseStatus`를 사용해서 상태코드를 지정해줘야 하는데, `ResponseEntity`를 활용해서 `ok()` 로 지정하는게 더 깔끔하지 않나요?

2023-09-29 02:39 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/problem/response/ShowProblemListResponse.java
> +
> 띄어쓰기가 되어있네요

수정했습니다

2023-09-29 02:43 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/problem/response/ShowProblemListResponse.java
> +        return new ShowProblemListResponse(listProblems,totalCount,page);
> Builder로 통일하자고 하지 않았나요 ?

수정했습니다

2023-09-29 02:47 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/review/response/CodeWithCodeLineNumberAndReviewResponse.java
> +    private List<ReviewWithRepliesResponse> reviewWithRepliesResponse;
> 클래스명은 컨벤션에 맞춰도, 필드명까지 이렇게 맞출 필요는 없을 것 같아요 그냥 reviews 라던가 ?

수정했습니다

2023-09-29 02:48 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/review/response/CodeWithCodeLineNumberAndReviewResponse.java
> +public class CodeWithCodeLineNumberAndReviewResponse {
> 그냥 CodeLineWithReview가 되어도 될 것 같지 않나요 ?

수정했습니다

2023-09-29 02:55 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/CommentWithRepliesResponse.java
> +    String photo;
> 접근제한자 다 빠져있네요

수정했습니다

2023-09-29 02:56 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/MainSolutionResponse.java
> +public class MainSolutionResponse {
> Main 말고 그냥 Solution으로 가도 될 것 같다고 말씀 드린 것 같은데, 왜 Main인가요 ? 제가 보기엔 차라리 MySolution으로 가도 될 것 같습니다.

수정했습니다

2023-09-29 02:57 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/ReviewWIthRepliesResponse.java
> +public class ReviewWIthRepliesResponse {
> 오타 났어요

수정했습니다

2023-09-29 03:02 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/ShowMySolutionDetailResponse.java
> +    // 문제
> 필요 없는 주석들 같습니다.

수정했습니다

2023-09-29 03:06 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/ShowSolutionDetailWithProblemAndCommentsResponse.java
> +public class ShowSolutionDetailWithProblemAndCommentsResponse {
> 여기는 그냥 ShowSolutionDetailResponse라고 가도 될 것 같은데욤 ..

수정했습니다

2023-09-29 03:17 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionAtSolutionListResponse.java
> +public class SolutionAtSolutionListResponse {
> SolutionAtSolutionListResponse는 이상한 것 같아요

풀이목록에서 사용하는 풀이 dto라 이렇게 작명했는데, 다른 식으로 어떻게 하는게 좋을까요? 저는 뾰족한 방법이 떠오르질 않네요 .. ㅜ

2023-09-29 03:19 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/solution/response/SolutionListResponse.java
> +    List<SolutionAtSolutionListResponse> solutionAtSolutionListResponses;
> 필드명은 그냥 solutions가 되어도 될 것 같아요

수정했습니다

2023-09-29 03:19 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/entity/comment/Comment.java
> +    private static final String DELETED_CONTENT = "삭제된 댓글입니다";
> 이거 제가 밑으로 옮겨놓은건데 다시 위로 옮긴 이유가 있나요 ?

위에 있는게 깔끔해 보여서 옮겼습니다!

2023-09-29 06:33 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/repository/solution/QueryDslSolutionRepositoryImpl.java
> +                .limit(6)
> 매직넘버는 안쓰면 좋을 것 같아요

밑에 말씀하신 것처럼 파라미터로 받도록 변경하겠습니다

2023-09-29 06:39 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +        List<Solution> solutionList = solutionRepository.findAllByProblem(mainSolution.getProblem());
> 정렬을 안하고 있는 것 같아요, 그리고 위의 mainSolution 또한 solutionList에 포함되어있을텐데, solutionList에서 찾는게 아니라 select절을 한번 더 날리는 이유가 궁금합니다.

컨트롤러 단에서 요청 자체가 solutionId를 가지고 들어오는거라 먼저 solutionId로 solution을 찾고 solution의 problem을 찾아서 쿼리를 날려야 합니다.

2023-09-29 06:44 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +        int likes = likesRepository.findAllBySolution(mainSolution).size();
> count 메서드도 사용할 수 있는 걸로 알고 있습니다. countBySolution등을 사용해보면 어ㅈ떨까요

수정했습니다

2023-09-29 07:18 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +        return solutionRepository.findAllByProblem(problem)
> member 도 where절에 들어가야 할 것 같은데 아닌가요 ? problem으로만 찾으면 남이 스크랩한 풀이도 들어갈 것 같아요.

최초 쿼리로 문제에 대한 모든 풀이를 가져오고 , 그 풀이 목록으로 내 풀이 목록을 만들어서 쓰는 방식으로 변경했습니다!

2023-09-29 07:19 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/SolutionService.java
> +                .stream().filter(solution -> solution.getScrapSolution() != null)
> 이건 쿼리문에 걸 수 있는 제약 아닌가요 ?

이것도 쿼리 새로 안날리고 solutionList 가져와서 찾는걸로 바꿨습니다!

2023-09-29 07:32 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
> +        assertThat(result).containsExactly(solution1,solution2,solution3,solution4,solution5,solution6);
> 위에 모든걸 다 순서대로 해놓으셔서, 저장순인지 좋아요순인지 알 수 없을 것 같아요

수정했습니다

2023-09-29 07:33 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/repository/solution/SolutionRepositoryTest.java
> +    @DisplayName("문제가 주어졌을 때 좋아요 순으로 상위 6개의 풀이를 정렬해서 가져올 수 있다")
> 차라리 find 쿼리의 limit를 동적으로 받아서 상위 6개 풀이를 가져올 수 있는걸 테스트 하지 마시고 1 ~ 2개 정도로 테스트 하는걸로 바꾸는게 어떤가요 ? 추후에 바뀔 수 있는 내용이잖아요 ?

좋은 것 같아요 수정했습니다!

2023-09-29 12:59 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/controller/SolutionController.java
> +        return ResponseEntity.ok().body(showMySolutionDetailResponse);
그냥 DTO를 반환하면 자동으로 ok입니다

2023-09-29 13:02 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/entity/comment/Comment.java
> +    private static final String DELETED_CONTENT = "삭제된 댓글입니다";
저는 사용하는 거랑 붙어 있는게 맞다고 생각해요 service 클래스도 아니고 위에는 엔티티의 필드들이 있고 밑에 도메인의 로직들이 있는건데 저는 둘이 분리 된다고 생각합니다.

2023-09-29 13:04 UTC, rlfrkdms1 approved these changes

2023-09-29 13:10 UTC, merged