[FEAT] 팔로우 목록보기
rlfrkdms1/Prog-rangers pull request #164
Opened 2023-10-03 10:42 UTC by jd99iam

## #163 

### 💡 PR 타입(하나 이상의 PR 타입을 선택해주세요)
* [ ] 기능 추가
* [ ] 기능 삭제
* [ ] 버그 수정
* [ ] 테스트코드 작성
* [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 📲 반영 브랜치
feat/163-followlist -> develop

### ❔ 변경 사항
팔로우 목록보기 기능을 추가했습니다

### 🔍 테스트 결과
- Repo 테스트 : 정상작동
- Service 테스트 : 정상작동

### 📰 참고 Reference
 
### ⚒️ 기타 사항

2023-10-05 08:55 UTC, rlfrkdms1 requested changes
테스트 코드가 훨씬 좋아진 것 같습니다 고생했습니다

2023-10-05 08:55 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/controller/FollowController.java
> +    @GetMapping("/follows")
지금 mypage는 prefix가 /mypage로 되어 있는데 통일하는게 어떤가요 ?

2023-10-05 08:55 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/dto/follow/response/ShowFollowListResponse.java
> +        private List<MemberResponse> recommendedFollowers;
recommendedFollowers보단 recommendedFollowings가 더 자연스러울 것 같아요
recommends로 줄여도 될 것 같긴합니다.

2023-10-05 08:55 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/repository/solution/SolutionCustomRepositoryImpl.java
> +    public Solution findOneRecentSolutionByMemberId(Long memberId){
limit를 인자로 받고 있는 것도 아닌데 query dsl로 한 이유가 있나요 ?

2023-10-05 08:55 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/repository/member/MemberRepositoryTest.java
> +    void getLimitRecommendedMembersTest(){
저번에 테스트 코드의 메서드 작명에 대한 코멘트 남겨드렸었는데 못보셨나요 ?

2023-10-05 08:55 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/repository/member/MemberRepositoryTest.java
> +        for (Member m : result){
이건 왜 있는걸까요?

2023-10-05 08:55 UTC, rlfrkdms1 commented on backend/src/test/java/com/prograngers/backend/repository/member/MemberRepositoryTest.java
> +
공백이 너무 긴 것 같아요 ..

2023-10-06 05:30 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/controller/FollowController.java
> +    @GetMapping("/follows")
> 지금 mypage는 prefix가 /mypage로 되어 있는데 통일하는게 어떤가요 ?

수정했습니다

2023-10-06 05:35 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/dto/follow/response/ShowFollowListResponse.java
> +        private List<MemberResponse> recommendedFollowers;
> recommendedFollowers보단 recommendedFollowings가 더 자연스러울 것 같아요 recommends로 줄여도 될 것 같긴합니다.

수정했습니다

2023-10-06 05:36 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/repository/solution/SolutionCustomRepositoryImpl.java
> +    public Solution findOneRecentSolutionByMemberId(Long memberId){
> limit를 인자로 받고 있는 것도 아닌데 query dsl로 한 이유가 있나요 ?

그냥 하려다가 뭐땜에 문제가 발생해서 바꿨는데 정확히 기억이 안나네용..

2023-10-06 05:40 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/repository/member/MemberRepositoryTest.java
> +        for (Member m : result){
> 이건 왜 있는걸까요?

제가 로그 찍어볼려고 했다가 지우는 걸 깜빡했네요 수정하겠습니다~

2023-10-06 05:44 UTC, jd99iam commented on backend/src/test/java/com/prograngers/backend/repository/member/MemberRepositoryTest.java
> +
> 공백이 너무 긴 것 같아요 ..

수정했습니다

2023-10-06 05:46 UTC, rlfrkdms1 approved these changes

2023-10-06 05:46 UTC, merged