[FEAT] 좋아요 누르기, 취소
rlfrkdms1/Prog-rangers pull request #57
Opened 2023-08-25 23:43 UTC by jd99iam

## #55 

### 💡 PR 타입(하나 이상의 PR 타입을 선택해주세요)
* [ ] 기능 추가
* [ ] 기능 삭제
* [ ] 버그 수정
* [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

### 📲 반영 브랜치
feature/55-likes-push-cancel -> 1-develop

### ❔ 변경 사항
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.

### 🔍 테스트 결과
테스트는 픽스처 수정 후 작성하겠습니다

### 📰 참고 Reference

### ⚒️ 기타 사항

2023-08-27 19:48 UTC, rlfrkdms1 requested changes

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/exception/badrequest/LikesAlreadyExistsException.java
> +public class LikesAlreadyExistsException extends AlreadyExistsException {
음 .. 그냥 `InvalidValue`로 하는것도 괜찮아 보이는데 변경한 이유가 있나요?

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
> +        }
find 관련한거 다 메서드 추출해서 예외처리 하는게 좋을 것 같아요

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
> +        if (targetLikes!=null){
위에서 orElse()면 찾은 like가 null일 때 나오는건데 왜 orElse에 null 을 넣어서 사용하나요 ? 그냥 get 사용하면 안되는 이유가 있나요 ?
그리고 이미 누른 좋아요인지 검증하고 싶다면, 아래와 같이 하는게 더 나아보이긴 한데 어떻게 생각하세요 ?
```java
public void validAlreadyPushedLike(Member member, Solution solution){
     if(likesRepository.findByMemberAndSolution(member, solution).isPresent()){
          throw new LikesAlreadyExistsException();
     }
}
```
그리고 지금 전부 target이라고 붙어있는데, target이 붙는 건 대상이 되는 것과 그렇지 않은것을 구분하는 경우라고 생각하는데 지금 해당 메서드에서는 중복되는 값이 보이지 않아서 (예로 두개의 solution이 사용된다거나) 왜 target을 사용하셨는지 궁금합니다.
직관적으로 보이려고 target을 사용하셨다면 위에 파라미터로 받은 것도 전부 targetMemberId, targetSolutionId가 되어야 맥락이 맞지 않나 싶어요

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
>          Member targetMember = memberRepository.findById(memberId).orElseThrow(MemberNotFoundException::new);
위의 메서드랑 중복되네요 메서드 추출이 좋아보입니다. find는 보통 다 중복돼서 사용되니 처음 사용하실 때 빼주시는게 가장 좋을 것 같아요

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
>          likesRepository.delete(targetLikes);
delete가 발생했는데 @Transactional 안붙은것 같습니다

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
>      public void pushLike(Long memberId, Long solutionId) {
`@Transactional` 빠졌습니다 애초에 클래스단에도 없어요 ㅠ

2023-08-27 19:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/exception/ErrorCode.java
커밋메세지는 `닉네임 이미 존재할 때 에러코드 추가` 라고 되어있는데 실제로 추가된건 `ALREADY_EXISTS_LIKE`네요

2023-08-28 03:30 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/exception/badrequest/LikesAlreadyExistsException.java
> +public class LikesAlreadyExistsException extends AlreadyExistsException {
> 음 .. 그냥 `InvalidValue`로 하는것도 괜찮아 보이는데 변경한 이유가 있나요?

Invalid value는 값이 유효하지 않다는 뜻인데 좋아요가 이미 존재하는 것이랑 관계가 없다고 생각했습니다

2023-08-28 03:39 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
> +        }
> find 관련한거 다 메서드 추출해서 예외처리 하는게 좋을 것 같아요

반영했습니다

2023-08-28 03:52 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
> +        if (targetLikes!=null){
> 위에서 orElse()면 찾은 like가 null일 때 나오는건데 왜 orElse에 null 을 넣어서 사용하나요 ? 그냥 get 사용하면 안되는 이유가 있나요 ? 그리고 이미 누른 좋아요인지 검증하고 싶다면, 아래와 같이 하는게 더 나아보이긴 한데 어떻게 생각하세요 ?
> 
> ```java
> public void validAlreadyPushedLike(Member member, Solution solution){
>      if(likesRepository.findByMemberAndSolution(member, solution).isPresent()){
>           throw new LikesAlreadyExistsException();
>      }
> }
> ```
> 
> 그리고 지금 전부 target이라고 붙어있는데, target이 붙는 건 대상이 되는 것과 그렇지 않은것을 구분하는 경우라고 생각하는데 지금 해당 메서드에서는 중복되는 값이 보이지 않아서 (예로 두개의 solution이 사용된다거나) 왜 target을 사용하셨는지 궁금합니다. 직관적으로 보이려고 target을 사용하셨다면 위에 파라미터로 받은 것도 전부 targetMemberId, targetSolutionId가 되어야 맥락이 맞지 않나 싶어요

이미 누른 좋아요인지 검증하는 방식은 말씀하신 방식이 더 나아 보여서 수정했습니다. 
그리고 파라미터로는 memberId를 받아서 repository를 활용해 찾은 후에 예외처리까지 해서 찾은 대상이 target이 된다는 느낌으로 사용했습니다. 설명을 들어도 별로시라면 수정하겠습니다

2023-08-28 03:53 UTC, jd99iam commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
>      public void pushLike(Long memberId, Long solutionId) {
> `@Transactional` 빠졌습니다 애초에 클래스단에도 없어요 

LikesService의 메서드 2개 다 transactional(readonly=false)이므로 서비스 단에 @transactional 을 붙이겠습니다

2023-08-28 07:48 UTC, rlfrkdms1 commented on backend/src/main/java/com/prograngers/backend/service/LikesService.java
> +        if (targetLikes!=null){
음 그렇군요 memberId에서 찾아져야 target이 된다 ! 라는 말씀이신거죠
좋습니다 생각하신대로 해주세요

2023-08-28 07:48 UTC, rlfrkdms1 approved these changes

2023-08-28 07:54 UTC, jd99iam commented
리뷰 감사합니다 ^^

2023-08-28 07:54 UTC, merged